version: '3.3'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234qwerty
      - POSTGRES_USER=helpdesk-history-user
      - POSTGRES_DB=helpdeskhistorydb
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5434}:5432