server:
  port: 8082

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

    prefer-ip-address: true

spring:
  application:
    name: helpdesk-history-service
  security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://localhost:8484/auth/realms/Helpdesk-gateway-app/protocol/openid-connect/certs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/helpdeskhistorydb
    username: helpdesk-history-user
    password: "1234qwerty"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml