spring:
  application:
    name: history-service
  config:
    import: optional:configserver:http://localhost:8888
    name: history-service
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true