spring:
  application:
    name: history-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: history-service
      discovery:
        enabled: true
        service-id: config-server